name: Deploy GitHub Pages
run-name: Deploy Website to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run deploy command
        env:
          USERNAME: ${{ secrets.USERNAME }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

        run: |
          git remote set-url origin https://$USERNAME:$GH_TOKEN@github.com/$USERNAME/blarknes.github.io.git
          npm run deploy
