name: Deploy GitHub Pages
run-name: Deploy Website to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run deploy command
        env:
          EMAIL: ${{ secrets.USER_EMAIL }}
          NAME: ${{ secrets.USER_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          git config --global user.email $EMAIL
          git config --global user.name $NAME
          npm run deploy
